stages:
  Data_Ingestion:
    cmd: python signLanguage\pipeline\training_pipeline.py
    deps:
      - signLanguage\pipeline\training_pipeline.py
      - config/config.yaml

    outs: 
      -  artifacts/data_ingestion/data.zip
      -  artifacts/data_ingestion/data