artifats_root: artifacts

Data_Ingestion:
  dir: artifacts/data_ingestion
  url: https://universe.roboflow.com/ds/2vScLVdC10?key=ssS8KdEzkb
  local_folder: artifacts/data_ingestion/data.zip
  unzip_folder: artifacts/data_ingestion/data
